service: aws-nodejs

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-2
  environment:
    REVIEWS_TABLE: "${self:service}-${opt:stage, self:provider.stage}-api"


functions:
  hello:
    handler: reviews/handler.hello